# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e64381c0b5464763d2703b2c79e499727b4e4c4b7a55771cb713bfd0a501af3aae715713bb0335a3cabcc30626bdc448f34e40effd0e0d0b00a0c3be43be2d3

test:
  secret_key_base: 6720cd6ebc0122ac95697be407b73f153c1ebb73c4c3ea29c3879595400b9e50a547d3acb0488eb8dc0a1bea337446a7075bb783b84c42a4577f62011ff858a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
